// The predicate set (JT2). `alphabets/predicates.<corpus>.yaml` — reviewed,
// versioned and committed, under the same discipline as the alphabet, and for
// the same reason: a predicate decides what a fact base contains, so a
// predicate that changes silently changes every figure derived from it.
//
// A predicate is never constructed at runtime and never generated by a model.
// The vendor's own framing agrees — "possible outputs and structure are
// defined in advance" — but the reason here is polyx's: a predicate is a claim
// about the corpus that a person has to accept (JF4.1), and a claim nobody
// wrote down is a claim nobody can refuse.
//
// This parser lives in the free half although the vendor adapter does not. An
// annotation line is uninterpretable without the predicate's id, fact name and
// bands, and the free half has to be able to read an annotation file to
// produce its report. Parsing YAML needs no key and no network.
//
// The load-time rules below are mostly ordinary schema validation. Two are not,
// and they are the point of the file:
//
//   `type` is not a field           every predicate is a noul (JT2.1)
//   `quadrant: sequence-unknown`    refused outright (JF2.4, A3)
import { readFileSync } from 'node:fs';
import { parse } from 'yaml';
import {
  validateBands,
  type Bands,
  type Calibration,
  type Predicate,
  type PredicateStatus,
  type PredicateWindow,
  type Quadrant,
} from './observation.ts';

export interface PredicateSet {
  corpus: string;
  /** Bumped by any change to a question, source or bands (JF1.4). Pins the annotation file. */
  version: number;
  model: string;
  /** The redaction profile applied before any text leaves the machine (JT7.1). */
  redaction: string;
  predicates: Predicate[];
}

export class PredicateSetError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PredicateSetError';
  }
}

// A declaration, not a const arrow: control-flow narrowing after a
// never-returning call needs one, and every check below relies on it.
function fail(msg: string): never {
  throw new PredicateSetError(msg);
}

const STATUSES: readonly PredicateStatus[] = ['proposed', 'real', 'not_real', 'retired'];
const WINDOWS: readonly PredicateWindow[] = ['event', 'before', 'sessionBefore'];
const QUADRANTS: readonly Quadrant[] = ['text-unknown', 'text-closed', 'sequence-closed', 'sequence-unknown'];

/** `event.text`, `episode.text`, or `slot.<name>`. */
const SOURCE = /^(event\.text|episode\.text|slot\.[A-Za-z_][A-Za-z0-9_]*)$/;

/**
 * Warnings are returned rather than thrown. A `sequence-closed` predicate is
 * legal and probably a waste of a model call; that is a judgement for the
 * reviewer, and the tool's job is to say so rather than to rule.
 */
export interface PredicateWarning {
  predicate: string;
  message: string;
}

function parseQuadrant(v: unknown, w: string, id: string, warnings: PredicateWarning[]): Quadrant {
  if (typeof v !== 'string' || !(QUADRANTS as readonly string[]).includes(v)) {
    fail(`${w}: quadrant is required and must be one of ${QUADRANTS.join(', ')}`);
  }
  const q = v as Quadrant;
  if (q === 'sequence-unknown') {
    // The measured case, and the reason this field exists. Asked "was income
    // verified?" over twelve matched cases where the record is equally silent
    // in all twelve, the model answered NOT VERIFIED twelve times out of
    // twelve and was right half the time. It was not failing; it was applying
    // the closed-world assumption perfectly to a partial record.
    fail(
      `${w}: quadrant 'sequence-unknown' is prohibited (JF2.4). This predicate asks what happened in the WORLD over a record that may not mention it, and a model reading a text will answer from the text's silence. Ask what the text STATES instead — "does this message state that X was done?" — and declare it assert-only.`,
    );
  }
  if (q === 'sequence-closed') {
    warnings.push({
      predicate: id,
      message: 'quadrant is sequence-closed: the sequence decides and the log is complete by construction, so an ordinary condition over the event log answers this exactly and for free. Write the if-statement rather than paying for a model call.',
    });
  }
  return q;
}

function parseBands(v: unknown, w: string, id: string): Bands {
  if (typeof v !== 'object' || v === null) fail(`${w}: bands is required`);
  const b = v as Record<string, unknown>;
  if (typeof b.assertAt !== 'number') fail(`${w}: bands.assertAt must be a number`);
  if (typeof b.refuteAt !== 'number') fail(`${w}: bands.refuteAt must be a number (use a negative value for assert-only)`);
  const bands: Bands = { assertAt: b.assertAt, refuteAt: b.refuteAt };
  validateBands(id, bands); // JT4.1, JT4.3 — throws a PredicateError naming the id
  return bands;
}

function parseCalibration(v: unknown, w: string): Calibration {
  if (typeof v !== 'object' || v === null) fail(`${w}: calibration must be a map`);
  const c = v as Record<string, unknown>;
  const num = (k: string): number => {
    const x = c[k];
    if (typeof x !== 'number') fail(`${w}: calibration.${k} must be a number`);
    return x as number;
  };
  const str = (k: string): string => {
    const x = c[k];
    if (typeof x !== 'string' || !x) fail(`${w}: calibration.${k} must be a non-empty string`);
    return x as string;
  };
  if (typeof c.labels !== 'object' || c.labels === null) fail(`${w}: calibration.labels must be a map of true/false counts`);
  const labels = c.labels as Record<string, unknown>;
  if (typeof labels.true !== 'number' || typeof labels.false !== 'number') fail(`${w}: calibration.labels needs numeric true and false counts`);
  const out: Calibration = {
    at: str('at'),
    corpusRevision: str('corpusRevision'),
    alphabetVersion: num('alphabetVersion'),
    n: num('n'),
    labels: { true: labels.true, false: labels.false, ...(typeof labels.unsure === 'number' ? { unsure: labels.unsure } : {}) },
    assertPrecision: num('assertPrecision'),
    refutePrecision: c.refutePrecision === null || c.refutePrecision === undefined ? null : num('refutePrecision'),
    withheldFraction: num('withheldFraction'),
    reviewer: str('reviewer'),
  };
  if (c.observed !== undefined) {
    const o = c.observed as Record<string, unknown>;
    if (typeof o !== 'object' || o === null || !Array.isArray(o.true) || !Array.isArray(o.false)) {
      fail(`${w}: calibration.observed must hold the observed p on each label`);
    }
    out.observed = { true: o.true as number[], false: o.false as number[] };
  }
  if (typeof c.labelSeparation === 'number') out.labelSeparation = c.labelSeparation;
  return out;
}

export function parsePredicateSet(text: string, where = 'predicates'): { set: PredicateSet; warnings: PredicateWarning[] } {
  const doc = parse(text) as Record<string, unknown>;
  if (typeof doc !== 'object' || doc === null) fail(`${where}: not a document`);
  if (typeof doc.corpus !== 'string' || !doc.corpus) fail(`${where}: corpus is required`);
  const corpus = doc.corpus;
  if (!Number.isInteger(doc.version) || (doc.version as number) < 1) fail(`${where}: version must be an integer >= 1`);
  const version = doc.version as number;
  // The model id is part of the artefact: a probability is a figure of one
  // model, and `jev-latest` moving underneath a pinned manifest is the open
  // risk this field exists to make visible. Pin a dated id the moment the
  // vendor exposes one.
  if (typeof doc.model !== 'string' || !doc.model) fail(`${where}: model is required — the figure a predicate produces is a figure of one model`);
  const model = doc.model;
  // JT7.2, failing closed. A corpus whose redaction is not declared cannot be
  // annotated, and the refusal belongs here rather than at the moment of
  // egress: by then someone has already configured a key.
  if (typeof doc.redaction !== 'string' || !doc.redaction) {
    fail(`${where}: redaction is required — naming the profile applied before any text leaves the machine (JT7.1). A corpus with no declared profile cannot be annotated.`);
  }
  const redaction = doc.redaction;
  if (!Array.isArray(doc.predicates)) fail(`${where}: predicates must be a list`);

  const warnings: PredicateWarning[] = [];
  const seenId = new Set<string>();
  const seenFact = new Set<string>();

  const predicates: Predicate[] = (doc.predicates as unknown[]).map((raw, i) => {
    const w = `${where}: predicates[${i}]`;
    if (typeof raw !== 'object' || raw === null) fail(`${w}: must be a map`);
    const p = raw as Record<string, unknown>;
    if (typeof p.id !== 'string' || !p.id) fail(`${w}: id is required`);
    const id = p.id;
    if (seenId.has(id)) fail(`${w}: duplicate id '${id}'`);
    seenId.add(id);

    // JT2.1 and JT2.2. `type` is not a field: every predicate is a noul.
    // `choice` returns a categorical distribution over MUTUALLY EXCLUSIVE
    // options, so asked of a multi-intent input it drops the other intents —
    // correct behaviour for a question we should not have asked. A silently
    // discarded intent is the failure mode polyx exists to prevent, and a
    // battery of assert-only nouls costs nothing because sampling is parallel.
    if (p.type !== undefined) {
      fail(`${w}: 'type' is not a field. Every predicate is a noul (JT2.1). For a set of alternatives declare one assert-only predicate per alternative; the battery costs what one question costs.`);
    }

    if (typeof p.fact !== 'string' || !p.fact.startsWith('obs.') || p.fact.length <= 4) {
      fail(`${w}: fact must be namespaced 'obs.<name>' (JF1.3), so an observed fact is distinguishable from a slot everywhere it appears`);
    }
    const fact = p.fact;
    if (seenFact.has(fact)) fail(`${w}: two predicates produce the fact '${fact}'; the second would overwrite the first`);
    seenFact.add(fact);

    if (typeof p.status !== 'string' || !(STATUSES as readonly string[]).includes(p.status)) {
      fail(`${w}: status must be one of ${STATUSES.join(', ')}`);
    }
    const status = p.status as PredicateStatus;
    const quadrant = parseQuadrant(p.quadrant, w, id, warnings);

    if (typeof p.source !== 'string' || !SOURCE.test(p.source)) {
      fail(`${w}: source must be 'event.text', 'episode.text' or 'slot.<name>'`);
    }
    const source = p.source;
    if (typeof p.window !== 'string' || !(WINDOWS as readonly string[]).includes(p.window)) {
      fail(`${w}: window must be one of ${WINDOWS.join(', ')}`);
    }
    const window = p.window as PredicateWindow;
    if (typeof p.question !== 'string' || !p.question.trim()) fail(`${w}: question is required`);
    const question = p.question.trim();

    const out: Predicate = {
      id,
      fact,
      status,
      quadrant,
      source,
      window,
      question,
      bands: parseBands(p.bands, w, id),
    };

    if (p.criteria !== undefined) {
      const c = p.criteria as Record<string, unknown>;
      if (typeof c !== 'object' || c === null || typeof c.true !== 'string' || typeof c.false !== 'string') {
        fail(`${w}: criteria needs a true and a false description`);
      }
      out.criteria = { true: c.true, false: c.false };
    }
    if (p.calibration !== undefined) out.calibration = parseCalibration(p.calibration, w);

    // JT2.4 — inert-by-omission is not permitted to look like configured. A
    // predicate marked real with no calibration would read, to anyone
    // skimming, as a predicate in service.
    if (status === 'real' && !out.calibration) {
      fail(`${w}: status is 'real' but there is no calibration block (JT2.4). A predicate is inert until it has one; say 'proposed' until it is calibrated.`);
    }

    // A4.1, from Control A: handing the model a wider record made it MORE
    // confident and no more correct where the missing fact was missing from
    // the wider window too. Not an error — some questions genuinely span
    // turns — but the reviewer should have decided it rather than defaulted.
    if (out.source === 'episode.text' || out.window !== 'event') {
      warnings.push({
        predicate: id,
        message: `reads ${out.source} over window '${out.window}': a wider window is not free. It is more expensive to recalibrate, because any change to segmentation changes its input (JT2.3), and a more complete-looking record raises the model's confidence without raising its accuracy when the fact is absent from the wider window too.`,
      });
    }

    return out;
  });

  return {
    set: { corpus, version, model, redaction, predicates },
    warnings,
  };
}

export function loadPredicateSet(file: string): { set: PredicateSet; warnings: PredicateWarning[] } {
  return parsePredicateSet(readFileSync(file, 'utf8'), file);
}

/** The predicates that actually emit facts: adjudicated real AND calibrated (JF3.1, JF4.1). */
export function activePredicates(set: PredicateSet): Predicate[] {
  return set.predicates.filter((p) => p.status === 'real' && p.calibration !== undefined);
}

/**
 * Declared but emitting nothing, with the reason. What `audit` reports (JT9.1)
 * — and the shape of the backlog, now that cost is not the constraint and
 * sixty human labels per predicate is.
 */
export function inertPredicates(set: PredicateSet): Array<{ predicate: Predicate; reason: string }> {
  const out: Array<{ predicate: Predicate; reason: string }> = [];
  for (const p of set.predicates) {
    if (p.status === 'real' && p.calibration) continue;
    if (p.status === 'proposed') out.push({ predicate: p, reason: p.calibration ? 'awaiting adjudication' : 'uncalibrated' });
    else if (p.status === 'real') out.push({ predicate: p, reason: 'uncalibrated' });
    else out.push({ predicate: p, reason: p.status === 'retired' ? 'retired' : 'adjudicated not real' });
  }
  return out;
}

/**
 * A calibration is stale when what it was measured against has moved (JF3.5).
 * Stale makes a predicate INERT rather than trusted: the failure is a loss of
 * coverage, which is recoverable, rather than a wrong answer, which is not.
 */
export function isStale(p: Predicate, corpusRevision: string, alphabetVersion: number): boolean {
  const c = p.calibration;
  if (!c) return true;
  return c.corpusRevision !== corpusRevision || c.alphabetVersion !== alphabetVersion;
}

/**
 * JF4.3 — the `obs.*` facts a rule's conditions mention that no `real`,
 * calibrated predicate produces. A rule that depends on one cannot be
 * adjudicated real: it would be served, its condition would be unknown at
 * every request, and it would abstain forever while looking like a rule in
 * service. The dependency is checked at adjudication time and named.
 */
export function unproducedFacts(conditions: ReadonlyArray<{ fact: string }>, set: PredicateSet | null): string[] {
  const produced = new Set(set ? activePredicates(set).map((p) => p.fact) : []);
  return [...new Set(conditions.map((c) => c.fact).filter((f) => f.startsWith('obs.') && !produced.has(f)))].sort();
}
