// The synthetic fixture corpus adapter. The corpus is generated by
// test/fixtures/synthetic/generate.mjs with a KNOWN planted rule set, and is
// the test oracle for everything downstream: provenance, contradiction,
// redaction and the unknown-event gate all have their ground truth here.
//
// Source shape (one JSON file):
//   { corpus, interactions: [ { id, operator, team, agent, startedAt, outcome?,
//       turns: [ { speaker, intent?, button?, event?, text?, slots?, result? } ] } ] }
//
// `text` is read and DISCARDED. It exists in the fixture precisely so the
// redaction scan can prove free text never reaches a stored artefact.
import { readFileSync } from 'node:fs';
import type { Scalar } from '../record.ts';
import type { Adapter, RawEvent, RawInteraction } from './types.ts';

interface SyntheticTurn {
  speaker: 'customer' | 'agent' | 'action' | 'system';
  intent?: string;
  button?: string;
  event?: string;
  text?: string;
  slots?: Record<string, Scalar>;
  result?: 'ok' | 'failed' | 'refused';
  /** Milliseconds after the previous turn. Default 1000. */
  gapMs?: number;
}

interface SyntheticInteraction {
  id: string;
  operator: string;
  team?: string;
  agent?: string;
  startedAt: number;
  outcome?: string;
  turns: SyntheticTurn[];
}

interface SyntheticCorpus {
  corpus: string;
  interactions: SyntheticInteraction[];
}

export const syntheticAdapter: Adapter = {
  name: 'synthetic',
  async read(source: string): Promise<RawInteraction[]> {
    const doc = JSON.parse(readFileSync(source, 'utf8')) as SyntheticCorpus;
    return doc.interactions.map((si, ii) => {
      let at = si.startedAt;
      const events: RawEvent[] = si.turns.map((t, ti) => {
        if (ti > 0) at += t.gapMs ?? 1000;
        const features: Record<string, Scalar> = { speaker: t.speaker };
        if (t.intent !== undefined) features.intent = t.intent;
        if (t.button !== undefined) features.button = t.button;
        if (t.event !== undefined) features.event = t.event;
        const e: RawEvent = {
          at,
          features,
          slots: { ...(t.slots ?? {}) },
          raw: { file: source, path: `/interactions/${ii}/turns/${ti}` },
        };
        if (t.result !== undefined) e.result = t.result;
        return e;
      });
      const actor: RawInteraction['actor'] = { operatorId: si.operator };
      if (si.team !== undefined) actor.teamId = si.team;
      if (si.agent !== undefined) actor.agentId = si.agent;
      // Every synthetic interaction is one task; the planted truth is one episode.
      const out: RawInteraction = { id: si.id, corpus: doc.corpus, actor, startedAt: si.startedAt, events, hints: { expected_episodes: 1 } };
      if (si.outcome !== undefined) {
        const last = events[events.length - 1];
        out.outcome = { label: si.outcome, at: last?.at ?? si.startedAt, lagMs: 0, source: 'in_band' };
      }
      return out;
    });
  },
};
